### ISSUE TITLE
[feature] format block code in markdown

### ISSUE THREAD

**Issue by ccforeverd** [shfshanyue/markdown-read#4]
``` js
let obj = {
    name: 'Gopal',
    age: Infinity}let originObj = JSON.stringify(obj)console.log(originObj) // {"name":"Gopal","age":null}
}
```

像上面的代码, 在微信页面中, 被读取后变成了

``` text
```auto
let obj = {  name: 'Gopal',  age: Infinity}let originObj = JSON.stringify(obj)console.log(originObj) // {"name":"Gopal","age":null}
\```
```

希望可以格式化 markdown 中的代码块

我搜索了网络没有找到合适的工具, 所以提了 issues, 希望大佬有时间给出建议

感谢!

**Comment by shfshanyue** [comment]
这个有可能是微信编辑器(或者第三方)的问题，就是它并没有把 codeblock 正确的渲染成 html，这里可以提供个地址吗

**Comment by ccforeverd** [comment]
> 这个有可能是微信编辑器(或者第三方)的问题，就是它并没有把 codeblock 正确的渲染成 html，这里可以提供个地址吗

我使用的这个地址做的测试: <https://mp.weixin.qq.com/s/1Ze6aUAHNcWH9bVAhukaJg>

**Comment by shfshanyue** [comment]
![image](https://user-images.githubusercontent.com/13389461/115392423-209a6600-a213-11eb-8c57-1f9d0579fcbc.png)

这个感觉是他的编辑器有问题

**Comment by ccforeverd** [comment]
嗷, 可以通过 turndown 来解决吗? 我也研究一下
